// Trotxi brand ramp for Fluent UI v9 — generated by the Fluent Theme Designer
// (react.fluentui.dev → Theme → Theme Designer) seeded from the app primary
// #013215 (app_colors.dart). Generated, not hand-derived: the designer's curve
// passes Fluent's contrast checks when used in tokens. Shade 30 (#013114) is
// the key colour snapped into that curve; shade 160 (#D7DFD9) lands near the
// design deck's #BDCABE accent, so the palette holds together end to end.
//
// Seam file (#174): move it into your src/ tree when scaffolding the console
// (strategy repo, docs/ops-console.md §2.1). If the brand colour ever changes,
// regenerate the ramp in the designer — do not hand-tweak individual shades,
// that is how contrast bugs are born.

import {
  createDarkTheme,
  createLightTheme,
  type BrandVariants,
  type Theme,
} from '@fluentui/react-components';

export const trotxiBrand: BrandVariants = {
  10: '#010401',
  20: '#081D0D',
  30: '#013114',
  40: '#123D21',
  50: '#23492E',
  60: '#33563C',
  70: '#42634A',
  80: '#527058',
  90: '#617D67',
  100: '#718A76',
  110: '#829886',
  120: '#92A696',
  130: '#A3B4A6',
  140: '#B4C2B7',
  150: '#C6D0C8',
  160: '#D7DFD9',
};

export const trotxiLight: Theme = createLightTheme(trotxiBrand);

export const trotxiDark: Theme = {
  ...createDarkTheme(trotxiBrand),
  // The designer's own dark-theme legibility overrides: brand foregrounds
  // brighten two steps so text on dark surfaces keeps its contrast ratio.
  colorBrandForeground1: trotxiBrand[110],
  colorBrandForeground2: trotxiBrand[120],
};
